### ISSUE TITLE
Empty page when installing via Helm chart

### ISSUE THREAD

**Issue by nielstenboom** [sureshamk/flux-ui#9]
Hi there,

Great job on this project. However I ran into a minor issue.

I installed the project via the helm chart, however I'm seeing an empty page. I checked into the console and saw that it was making a request to `/api/api/flux/v6/services` so I added the `BASE_API: "/"` value in this values.yaml and this fixed it.

**Steps to reproduce**

Install the ui via the flux helm-operator
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-ui
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: flux-ui
  chart:
    repository: https://raw.githubusercontent.com/sureshamk/flux-ui/master/flux-ui
    name: flux-ui
    version: 0.1.0
  values:
    config:
      END_POINT: "http://flux:3030"
```
Navigate to the ui and you can see that it's not working.

**Proposed solution**
Change the default value of `BASE_API` in the chart to `"/"`
